/**
 * Realistic sample payloads for every ARD §5.3/§5.4 shape, mirrored from the worked examples in
 * ARD.md and the PRD §6 demo script (Longi Hi-MO7 550W @ RM 467, 8S×3P, Voc 396.8V, Vmp 332.0V,
 * 91% confidence, 9.2yr payback, Huawei SUN2000-10KTL-M1). Develop cards/pages against these
 * before the backend contract lands — the shapes are frozen by ARD.md §5.
 */
import type {
  AnalyticsOverview,
  ChatMessage,
  ComponentRow,
  DesignReport,
  OverviewResponse,
  Project,
  SupplierQuote,
  Vendor,
} from "./types";

export const fixtureProject: Project = {
  id: 5,
  name: "Greenfield — KL Tech Park",
  client_name: "Greenfield Development Sdn Bhd",
  site_location: "KL Tech Park, Bukit Jalil",
  region: "Selangor",
  phase: "Design & Procurement",
  total_panels: 20,
  contract_value: 58000,
  status: "active",
  created_at: "2026-08-24T02:00:00Z",
  state: "Selangor",
  system_type: "on_grid",
  monthly_consumption_kwh: 950,
  tariff_category: "commercial",
  roof_area_m2: 42,
  roof_tilt_deg: 10,
  roof_azimuth_deg: 5,
  shading_factor: 0.95,
  obstructions: [{ kind: "water_tank", count: 1 }],
};

export const fixtureVendors: Vendor[] = [
  {
    id: 3,
    company_name: "SunTech Materials Sdn Bhd",
    region: "Selangor",
    contact_email: "sales@suntechmaterials.com.my",
    on_time_rate: 96,
    unit_price_myr: 467,
    specialization: "Modules & Inverters",
    is_active: true,
    created_at: "2025-11-02T03:00:00Z",
    bnef_tier: 1,
    brands_carried: ["Longi", "Huawei"],
    country: "Malaysia",
    quote_currency: "MYR",
  },
  {
    id: 7,
    company_name: "Apex Solar Trading",
    region: "Johor",
    contact_email: "quotes@apexsolar.com",
    on_time_rate: 88,
    unit_price_myr: 512,
    specialization: "Panels",
    is_active: true,
    created_at: "2025-12-10T03:00:00Z",
    bnef_tier: 2,
    brands_carried: ["SolarEdge Panels Co"],
    country: "Malaysia",
    quote_currency: "USD",
  },
];

export const fixtureComponents: ComponentRow[] = [
  {
    id: 12,
    kind: "module",
    manufacturer: "Longi",
    model: "Hi-MO7 LR5-72HTH-550M",
    tier: 1,
    rated_wp: 550,
    vmp: 41.5,
    voc: 49.6,
    imp: 13.2,
    isc: 14.0,
    temp_coeff_voc_pct_per_c: -0.26,
    efficiency_pct: 21.3,
    cell_tech: "N-type TOPCon",
    area_m2: 2.58,
    source: "CEC",
    created_at: "2026-01-15T00:00:00Z",
  },
  {
    id: 44,
    kind: "inverter",
    manufacturer: "Huawei",
    model: "SUN2000-10KTL-M1",
    tier: 1,
    ac_rating_kw: 10,
    max_dc_input_kw: 15,
    mppt_min_v: 120,
    mppt_max_v: 500,
    max_dc_voltage_v: 1080,
    max_input_current_per_mppt_a: 26,
    mppt_count: 2,
    phase: "three",
    euro_efficiency_pct: 98.6,
    has_anti_islanding: true,
    source: "CEC",
    created_at: "2026-01-15T00:00:00Z",
  },
];

export const fixtureSupplierQuote: SupplierQuote = {
  id: 7,
  supplier_name_raw: "SunTech Materials Sdn Bhd",
  vendor_id: 3,
  vendor_matched: true,
  source_filename: "quote-suntech-aug26.pdf",
  currency: "MYR",
  fx_rate_to_myr: 1.0,
  parse_status: "parsed",
  page_count: 2,
  subtotal_myr: 51240.0,
  parse_notes: "Line 4 unit ambiguous ('nos') — assumed pieces.",
  line_items: [
    {
      line_no: 1,
      category: "module",
      manufacturer: "Longi",
      model: "Hi-MO7 LR5-72HTH-550M",
      description: "550Wp N-type TOPCon monocrystalline module",
      quantity: 20,
      unit: "pcs",
      unit_price: 467.0,
      currency: "MYR",
      unit_price_myr: 467.0,
      line_total_myr: 9340.0,
      rated_wp: 550,
      price_per_wp_myr: 0.849,
      warranty_years: 25,
      lead_time_days: 21,
      bnef_tier1: true,
      tier_match_name: "LONGi Green Energy",
      flags: [],
    },
    {
      line_no: 2,
      category: "inverter",
      manufacturer: "Huawei",
      model: "SUN2000-10KTL-M1",
      description: "10kW three-phase string inverter, 2 MPPT",
      quantity: 1,
      unit: "unit",
      unit_price: 5800.0,
      currency: "MYR",
      unit_price_myr: 5800.0,
      line_total_myr: 5800.0,
      rated_wp: null,
      price_per_wp_myr: null,
      warranty_years: 10,
      lead_time_days: 14,
      bnef_tier1: null,
      tier_match_name: null,
      flags: [],
    },
  ],
  summary: {
    total_wp: 11000,
    blended_price_per_wp_myr: 0.849,
    tier1_line_count: 1,
    flagged_line_count: 0,
  },
};

/** Mirrors ARD.md §5.3 verbatim — the frozen contract every card in components/cards/ renders from. */
export const fixtureDesignReport: DesignReport = {
  id: 12,
  project_id: 5,
  system_type: "on_grid",
  status: "pass",
  generated_at: "2026-08-31T09:12:00Z",
  confidence: {
    score: 91,
    band: "Detailed specification — installer to confirm string design",
    disclaimer: "AI-estimated, installer-confirmed",
    components: [
      { label: "Base — field photo count + standard parameters", delta: 85, applied: true, reason: "Panel count verified from field photo" },
      { label: "Parsed supplier quote", delta: 3, applied: true, reason: "Real unit pricing attached from SunTech Materials quote" },
      { label: "String validation", delta: 3, applied: true, reason: "8S × 3P validated PASS against Huawei SUN2000-10KTL-M1" },
      { label: "Site specifics", delta: 2, applied: true, reason: "Tilt 10°, azimuth 5°, shading 0.95 recorded on site" },
      { label: "Consumption on record", delta: 1, applied: true, reason: "950 kWh/mo metered, not estimated" },
      { label: "Manual panel count", delta: -10, applied: false, reason: "Not applied — count came from a field photo" },
      { label: "PSH fallback", delta: -4, applied: false, reason: "Not applied — Selangor state-average PSH used with no site pyranometer" },
    ],
  },
  site: {
    state: "Selangor",
    psh: 4.3,
    psh_source: "state_average",
    roof_area_m2: 42,
    net_area_m2: 40,
    max_panels: 19,
    efficiency: { base: 0.75, tilt: 1.0, azimuth: 0.98, shading: 0.95, temperature: 0.85, effective: 0.593 },
  },
  load: { monthly_kwh: 950, daily_kwh: 31.7, design_daily_wh: 38000, safety_factor: 1.2 },
  array: {
    panel_count: 20,
    module: {
      manufacturer: "Longi",
      model: "Hi-MO7 LR5-72HTH-550M",
      rated_wp: 550,
      vmp: 41.5,
      voc: 49.6,
      imp: 13.2,
      isc: 14.0,
      bnef_tier1: true,
    },
    actual_kwp: 11.0,
    required_kwp: 9.4,
    max_roof_kwp: 10.45,
    constrained: false,
    coverage_pct: 100,
    daily_generation_kwh: 28.06,
    self_consumed_kwh: 28.06,
    exported_kwh: 0,
    self_consumption_pct: 100,
  },
  strings: {
    series: 8,
    parallel: 3,
    config_label: "8S × 3P",
    panels_used: 24,
    orphan_panels: 4,
    vmp_string: 332.0,
    voc_string: 396.8,
    voc_cold_string: 396.8,
    voc_method: "flat_0.85_buffer",
    total_isc: 42.0,
    status: "pass",
    checks: [
      { id: "vmp_in_mppt", label: "String Vmp within MPPT window", expected: "120–500 V", actual: 332.0, unit: "V", passed: true, margin_pct: 33.6 },
      { id: "voc_cold_under_max", label: "Cold Voc under absolute max DC voltage", expected: "< 1080 V", actual: 396.8, unit: "V", passed: true, margin_pct: 63.3 },
      { id: "isc_under_mppt_limit", label: "Total Isc under MPPT current limit", expected: "< 52 A", actual: 42.0, unit: "A", passed: true, margin_pct: 19.2 },
    ],
  },
  inverter: {
    manufacturer: "Huawei",
    model: "SUN2000-10KTL-M1",
    ac_rating_kw: 10,
    max_dc_input_kw: 15,
    mppt_min_v: 120,
    mppt_max_v: 500,
    max_dc_voltage_v: 1080,
    dc_ac_ratio: 1.1,
    selected_by: "user",
    checks: [
      { id: "dc_ac_ratio_band", label: "DC:AC ratio within 1.2–1.5x band", expected: "1.2–1.5x", actual: 1.1, unit: "x", passed: false, margin_pct: -8.3 },
      { id: "max_dc_input_headroom", label: "Array kWp within inverter max DC input", expected: "≤ 15 kW", actual: 11.0, unit: "kW", passed: true, margin_pct: 26.7 },
      { id: "anti_islanding_present", label: "Anti-islanding protection present", expected: "required", actual: "present", unit: "", passed: true, margin_pct: null },
    ],
  },
  battery: null,
  bos: {
    groups: [
      {
        group: "DC Protection",
        items: [
          { item: "String DC fuse", spec: "1.25 × Isc per string", rating: "20 A gPV", standard: "IEC 62548", note: "Calculated 17.5 A → next standard size" },
          { item: "DC isolator", spec: "String Voc × 1.2", rating: "1000 V", standard: "IEC 62548", note: "178.6 V calculated → next standard rating" },
          { item: "DC surge protection device", spec: "Type 2, per combiner box", rating: "Type 2 SPD", standard: "IEC 62548", note: "One per combiner (parallel > 2)" },
          { item: "Combiner box", spec: "Required — 5 parallel strings", rating: "5-in / 1-out", standard: "IEC 62548", note: "parallel > 2 triggers a combiner" },
        ],
      },
      {
        group: "AC Protection",
        items: [
          { item: "AC MCB", spec: "I_ac × 1.25, three-phase", rating: "32 A", standard: "TNB TCG", note: "Ac current 15.1 A calculated" },
          { item: "AC surge protection device", spec: "Type 2, at point of interconnection", rating: "Type 2 SPD", standard: "IEC 62548", note: "—" },
          { item: "RCCB", spec: "Residual current device", rating: "30 mA", standard: "MS IEC 60947", note: "—" },
        ],
      },
      {
        group: "Cables",
        items: [
          { item: "DC string cable", spec: "≤ 15 m run, < 20 A", rating: "4 mm²", standard: "IEC 62548", note: "—" },
          { item: "AC interconnection cable", spec: "Ampacity ≥ I_ac × 1.25", rating: "6 mm²", standard: "TNB TCG", note: "Voltage drop budget ≤ 1.5%" },
        ],
      },
      {
        group: "Earthing",
        items: [
          { item: "Earth rod", spec: "Separate DC/AC, ≥ 16 mm Cu, 2.4 m", rating: "≤ 5 Ω", standard: "IEC 60364", note: "Measured at commissioning" },
        ],
      },
    ],
  },
  financial: {
    monthly_generation_kwh: 842,
    effective_tariff_myr: 0.4713,
    monthly_savings_myr: 397,
    annual_savings_myr: 4764,
    bill_before_myr: 448,
    bill_after_myr: 51,
    system_cost_myr: 44000,
    cost_range_myr: [35000, 50000],
    payback_years: 9.2,
    payback_range_years: [7.8, 11.0],
    export_kwh: 0,
    export_rate_myr: 0.18,
    rollover: false,
    projection: [
      { year: 1, cumulative_savings: 4764, cumulative_net: -39236 },
      { year: 5, cumulative_savings: 25281, cumulative_net: -18719 },
      { year: 9, cumulative_savings: 47932, cumulative_net: 3932 },
      { year: 15, cumulative_savings: 85431, cumulative_net: 41431 },
      { year: 25, cumulative_savings: 163808, cumulative_net: 119808 },
    ],
    assumptions: ["0.5%/yr module degradation", "3%/yr tariff escalation", "No export credit rollover (Solar ATAP)"],
  },
  equipment_tier: "premium",
  warnings: [{ level: "warn", code: "DCAC_RATIO_LOW", message: "DC:AC ratio 1.1x is below the 1.2x recommended minimum — inverter may be oversized for this array." }],
  assumptions: ["Temperature derating 0.85 fixed for Malaysian ambient", "PSH taken as the Selangor state average — no on-site pyranometer reading", "System cost estimated from the parsed SunTech Materials quote"],
};

export const fixtureOverview: OverviewResponse = {
  total_capacity_kwp: 187.4,
  active_projects: 4,
  open_rfqs: 3,
  po_value_myr: 214500,
  avg_confidence: 89,
  panels_installed: 341,
  co2_avoided_tonnes: 128.6,
  generation_trend: [
    { month: "2025-09", value: 14200 },
    { month: "2025-10", value: 15800 },
    { month: "2025-11", value: 13950 },
    { month: "2025-12", value: 12100 },
    { month: "2026-01", value: 16400 },
    { month: "2026-02", value: 17650 },
    { month: "2026-03", value: 19200 },
    { month: "2026-04", value: 20100 },
    { month: "2026-05", value: 21850 },
    { month: "2026-06", value: 22940 },
    { month: "2026-07", value: 21300 },
    { month: "2026-08", value: 19870 },
  ],
  spend_trend: [
    { month: "2025-09", value: 31200 },
    { month: "2025-10", value: 28400 },
    { month: "2025-11", value: 19800 },
    { month: "2025-12", value: 42100 },
    { month: "2026-01", value: 36500 },
    { month: "2026-02", value: 22900 },
    { month: "2026-03", value: 51200 },
    { month: "2026-04", value: 33700 },
    { month: "2026-05", value: 27600 },
    { month: "2026-06", value: 44900 },
    { month: "2026-07", value: 38200 },
    { month: "2026-08", value: 29500 },
  ],
};

export const fixtureAnalytics: AnalyticsOverview = {
  total_contract_value: 612000,
  total_spend: 348900,
  active_projects: 4,
  completed_projects: 2,
  total_panels_with_issues: 6,
  project_budgets: [
    { project_id: 1, name: "Johor Bahru Commercial Rooftop", region: "Johor", status: "active", contract_value: 210000, spend: 132000, budget_used_pct: 63, completion_pct: 58 },
    { project_id: 2, name: "Sungai Petani Residence", region: "Kedah", status: "active", contract_value: 42000, spend: 39500, budget_used_pct: 94, completion_pct: 91 },
    { project_id: 3, name: "Kuching Commercial Block C", region: "Sarawak", status: "active", contract_value: 178000, spend: 68900, budget_used_pct: 39, completion_pct: 34 },
    { project_id: 5, name: "Greenfield — KL Tech Park", region: "Selangor", status: "active", contract_value: 58000, spend: 8500, budget_used_pct: 15, completion_pct: 12 },
  ],
  vendor_leaderboard: [
    { vendor_id: 3, company_name: "SunTech Materials Sdn Bhd", region: "Selangor", specialization: "Modules & Inverters", on_time_rate: 96, total_orders: 14, total_spend: 189400 },
    { vendor_id: 7, company_name: "Apex Solar Trading", region: "Johor", specialization: "Panels", on_time_rate: 88, total_orders: 6, total_spend: 74200 },
  ],
  spend_trend: [
    { month: "2026-04", amount: 33700 },
    { month: "2026-05", amount: 27600 },
    { month: "2026-06", amount: 44900 },
    { month: "2026-07", amount: 38200 },
    { month: "2026-08", amount: 29500 },
  ],
  generated_at: "2026-08-31T09:00:00Z",
};

export const fixtureChatMessages: ChatMessage[] = [
  {
    id: 1,
    session_key: "web:demo",
    role: "user",
    content: "Extract this quote, normalize the unit economics, and check manufacturer tier status.",
    cards: [],
    attachments: [{ file_id: "f_quote_1", filename: "quote-suntech-aug26.pdf", url: "/uploads/quotes/quote-suntech-aug26.pdf", kind: "pdf", size: 184320 }],
    tool_trace: [],
    created_at: "2026-08-31T09:10:12Z",
  },
  {
    id: 2,
    session_key: "web:demo",
    role: "assistant",
    content:
      "Parsed the SunTech Materials quote — Longi Hi-MO7 550W at RM 467/unit (RM 0.849/Wp), confirmed BNEF Tier 1. Want me to check it against the Huawei 10kW string inverter?",
    cards: [{ card_type: "quote_parsed", data: fixtureSupplierQuote }],
    attachments: [],
    tool_trace: [{ name: "parse_supplier_quote", ok: true }],
    created_at: "2026-08-31T09:10:24Z",
  },
  {
    id: 3,
    session_key: "web:demo",
    role: "user",
    content: "Can we pair these panels with a standard 10kW Huawei string inverter?",
    cards: [],
    attachments: [],
    tool_trace: [],
    created_at: "2026-08-31T09:11:40Z",
  },
  {
    id: 4,
    session_key: "web:demo",
    role: "assistant",
    content:
      "8S × 3P clears every check — cold Voc 396.8V stays well under the 1080V limit, and Vmp 332.0V sits inside the MPPT window. DC:AC comes out to 1.1x. Confidence: 91.",
    cards: [
      { card_type: "feasibility", data: fixtureDesignReport },
      { card_type: "confidence", data: fixtureDesignReport.confidence },
    ],
    attachments: [],
    tool_trace: [{ name: "run_feasibility", ok: true }],
    created_at: "2026-08-31T09:12:05Z",
  },
];
